import 'package:ai_bot/controller/image_controller.dart';
import 'package:ai_bot/helper/global.dart';
import 'package:ai_bot/widget/custom_btn.dart';
import 'package:ai_bot/widget/custom_loading.dart';
import 'package:cached_network_image/cached_network_image.dart';
import 'package:flutter/material.dart';
import 'package:get/get_state_manager/src/rx_flutter/rx_obx_widget.dart';
import 'package:lottie/lottie.dart';

class ImageFeature extends StatefulWidget {
  const ImageFeature({super.key});

  @override
  State<ImageFeature> createState() => _ImageFeatureState();
}

class _ImageFeatureState extends State<ImageFeature> {
  final _c = ImageController();
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('AI Image Creator'),
        actions: [
          Obx(
            () => _c.status.value == Status.complete ?  IconButton(
                onPressed: _c.shareImage,
                padding: EdgeInsets.only(right: 6),
                icon: Icon(Icons.share)): SizedBox()
          )
        ],
      ),
      // download button
      floatingActionButton: Obx(() => _c.status.value == Status.complete
          ? Padding(
              padding: EdgeInsets.only(right: 6, bottom: 6),
              child: FloatingActionButton(
                onPressed: _c.downloadImage,
                shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.all(Radius.circular(15))),
                child: Icon(Icons.save_alt_rounded, size: 26),
              ),
            )
          : SizedBox()),
      // lidt of images generated by ai
      body: ListView(
          physics: BouncingScrollPhysics(),
          padding: EdgeInsets.only(
              top: mq.height * .02,
              bottom: mq.height * .1,
              left: mq.width * .04,
              right: mq.width * .04),
          children: [
            // box for user input
            TextFormField(
              controller: _c.textC,
              textAlign: TextAlign.center,
              minLines: 2,
              maxLines: null,
              onTapOutside: (e) => FocusScope.of(context).unfocus(),
              decoration: InputDecoration(
                  fillColor: Colors.white,
                  hintText:
                      'Imagine something wonderful & innovative\nType here & I will create for you',
                  hintStyle: TextStyle(fontSize: 14),
                  border: OutlineInputBorder(
                      borderRadius: BorderRadius.all(Radius.circular(20)))),
            ),
            Container(
                height: mq.height * .5,
                margin: EdgeInsets.symmetric(vertical: mq.height * .015),
                alignment: Alignment.center,
                child: _aiImage()),

            Wrap(
              children: _c.imageList
                  .map((e) => CachedNetworkImage(
                        imageUrl: e,
                        height: 100,
                        errorWidget: (context, url, error) => const SizedBox(),
                      ))
                  .toList(),
            ),
            // button for create
            CustomBtn(onTap: _c.searchAiImage, text: 'Create'),
          ]),
    );
  }

  // ai image
  Widget _aiImage() => ClipRRect(
        borderRadius: const BorderRadius.all(Radius.circular(10)),
        child: switch (_c.status.value) {
          Status.none =>
            Lottie.asset('assets/lottie/aihello.json', height: mq.height * .3),
          Status.complete => CachedNetworkImage(
              imageUrl: _c.url.value,
              placeholder: (context, url) => const CustomLoading(),
              errorWidget: (context, url, error) => const SizedBox(),
            ),
          Status.loading => const CustomLoading()
        },
      );
}
