name: ai_bot
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  # for lottie animations
  lottie: ^3.1.3

  #for hive Database
  hive: ^2.2.3
  isar_flutter_libs: ^4.0.0-dev.14
  # for accessing storage path
  path_provider: ^2.1.5

  # for state management
  get: ^4.6.6

  # for animation
  flutter_animate: ^4.5.0
  # for gemini google
  google_generative_ai: ^0.4.6
  http: ^1.2.2
  #for animated text
  animated_text_kit: ^4.2.2

  # for AI image generation
  cached_network_image: ^3.4.1
  # for saving image
  permission_handler: ^10.2.0
  image_gallery_saver_plus: ^3.0.5
  # for sharing image
  share_plus: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/chatbot.png"
  min_sdk_android: 23
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/chatbot.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/chatbot.png
    - assets/lottie/loading.json
    - assets/lottie/aiask.json
    - assets/lottie/aihello.json
    - assets/lottie/Aiwaving.json
